import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { StreamVideoProvider } from "@/providers/StreamClientProvider";
import React ,{ReactNode} from 'react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// const RootLayout =({children}:{children:ReactNode})=>{
//   return (
//     <main>
//       <StreamVideoProvider>
//         {children}
//       </StreamVideoProvider>
//     </main>
//   )
// }
// export default RootLayout;
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
      appearance={{
        layout:{
          logoImageUrl:'/icons/yoom-logo.svg',
          socialButtonsVariant:'iconButton'

        },
        variables:{
          colorText:'#252a41',
          colorPrimary:'#0E78F9',
          colorBackground:'#76ABDF',
          colorInputBackground:'#252a41',
          colorInputText:'#fff'

        }
      }}
      >
      <body
        className={`${geistSans.className} bg-dark-2`}>{children}
         <StreamVideoProvider>{children}</StreamVideoProvider>
      </body>
      </ClerkProvider>
    </html>
  );
}
